### ISSUE TITLE
Discord.js dependency is out of date and should be updated

### ISSUE THREAD

**Issue by dbolger** [kalempster/discord.js-menu-buttons#1]
I think this project may need to be updated to keep up to date with Discord.js changes that have been introduced. When I run a project I'm building using discord.js-menu-buttons, I get this warning:

`(node:104051) DeprecationWarning: BaseInteraction#isSelectMenu() is deprecated. Use BaseInteraction#isStringSelectMenu() instead.
`

I'm also getting these warnings when upgrading using yarn:
```
yarn upgrade v1.22.19
[1/4] Resolving packages...
warning discord.js-menu-buttons > discord.js > @discordjs/builders@0.16.0: no longer supported
warning discord.js-menu-buttons > discord.js > @discordjs/collection@0.7.0: no longer supported
```

While these aren't showstoppers, I think this project should be upgraded to support the latest Discord.js features.

**Comment by kalempster** [comment]
Addressed with ff7ab19510423f2358ef9d7bb3afa4199001b06b
